# prod 环境 — 3 副本，高资源，手动审批后才部署

image:
  repository: sven110sugar/cake-app
  tag: stable

replicas: 3

resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 2
    memory: 1Gi

service:
  type: ClusterIP
  port: 80
  targetPort: 5000

env:
  name: prod
  debug: "false"

namespace: prod
